### ISSUE TITLE
Issue with some Tensorflow versions

### ISSUE THREAD

**Issue by LauLauThom** [mpicbg-csbd/stardist-imagej#2]
Hi guys,
Very nice plugin, I just have some issues with some versions of tensorflow CPU.

If I use the latest CPU version (1.14.0 or so) I have some DLL initialisation issues reported in the shipped Tensorflow management tool, eventhough the dll file is there.
```
[Wed Mar 18 11:45:37 CET 2020] [WARNING] [] Could not load native TF library TF 1.14.0 CPU C:\Users\Laurent\Documents\fiji-win64\Fiji.app\lib\win64\tensorflow_jni.dll: A dynamic link library (DLL) initialization routine failed
```
However
- Version 1.5.0 works
- Version 1.2.0 just crashes Fiji ><

I have an intel Xeon X5660 on a Win10 machine, do you think it can be related to the age of the CPU ?

**Comment by maweigert** [comment]
Hi Laurent, 

> I have an intel Xeon X5660 on a Win10 machine, do you think it can be related to the age of the CPU ?

Indeed, your old CPU seems to be the culprit. 
According to 
https://www.tensorflow.org/install/pip#hardware-requirements
all tf version > 1.5 need a CPU with AVX instructions, which [your CPU lacks](https://ark.intel.com/content/www/de/de/ark/products/47921/intel-xeon-processor-x5660-12m-cache-2-80-ghz-6-40-gt-s-intel-qpi.html). So maybe sticking to 1.5 will do?

**Comment by LauLauThom** [comment]
Hi Martin,
Thanks for the quick reply ! Sure that will do !
Maybe this could be mentioned somewhere in the doc of CSBDeep too ? @frauzufall 

I think this issue could stay open so people coming across the same problem can find it easily :)

**Comment by uschmidt83** [comment]
Hi Laurent,

if I understand correctly, [most in-use CPUs have AVX since 2011](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions), hence CPUs without it seem to be very much an edge case. However, you could compile TensorFlow yourself or get a version that doesn't require AVX elsewhere (see [this](https://github.com/tensorflow/tensorflow/issues/24548)).

> I think this issue could stay open so people coming across the same problem can find it easily :)

I'd close this issue if you don't object, since people should be able to find it via search engines.

Best,
Uwe
